djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('',views.HomeView.as_view(),name='homepage'),
    path('bucket/', views.BucketView.as_view(),name='bucket'),
    path('bucket/delete/<key>/',views.BucketObjectDeleteView.as_view(), name='bucket_delete'),
    path('bucket/dowmload/<key>/', views.BucketObjectDownloadView.as_view(), name='bucket_download'),
    path('category/<slug:category_slug>/',views.CategoryView.as_view(), name='category_detail'),
    path('products/<slug:product_slug>/', views.ProductView.as_view(), name='product_detail')

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('create/', views.CreateOrderView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='coupon_apply'),
]

home/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='scategory', null=True,blank=True)
    is_sub = models.BooleanField(default=False)
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    @property
    def slug(self):
        return slugify(self.name)

    def get_absolute_url(self):
        return reverse('home:category_detail', args=[self.slug,])


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=200, unique=True)
    image = models.ImageField()
    description = RichTextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    @property
    def slug(self):
        return slugify(self.name)

    def get_absolute_url(self):
        return reverse('home:product_detail', args=[self.slug,])

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Category, Product
from .tasks import all_bucket_objects_task, delete_object_task, download_object_task
from django.contrib import messages
from utils import IsUserAdminMixin
from orders.forms import CartAddForm


class HomeView(View):
    def get(self,request):
        categories = Category.objects.filter(is_sub=False)
        products = Product.objects.all()
        return render(request,'home/homepage.html',{'categories': categories, 'products': products})


class CategoryView(View):
    def get(self, request, category_slug):
        products = Product.objects.filter(available=True)
        categories = Category.objects.all()
        category = [category for category in categories if category.slug == category_slug][0]
        products = products.filter(category=category)
        categories = Category.objects.filter(is_sub=False)
        return render(request, 'home/category_detail.html', {'products': products, 'categories': categories})


class ProductView(View):
    def get(self, request, product_slug):
        products = Product.objects.all()
        product = [product for product in products if product.slug == product_slug][0]
        form = CartAddForm()
        return render(request,'home/product.html',{'product':product, 'form': form})


class BucketView(IsUserAdminMixin, View):
    def get(self, request):
        objects = all_bucket_objects_task()
        return render(request, 'home/bucket.html', {'objects': objects})


class BucketObjectDeleteView(IsUserAdminMixin, View):
    def get(self, request, key):
        delete_object_task.delay(key)
        messages.success(request, 'This object will be deleted soon', 'info')
        return redirect('home:bucket')


class BucketObjectDownloadView(IsUserAdminMixin, View):
    def get(self, request, key):
        download_object_task.delay(key)
        messages.success(request, 'your download will start soon', 'info')
        return redirect('home:bucket')

home/templates/home/bucket.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Size</th>
      <th scope="col">Download</th>
        <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {%  for object in objects %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ object.Key }}</td>
      <td>{{ object.Size|filesizeformat }}</td>
      <td><a href="{% url 'home:bucket_download' object.Key %}">Download</a></td>
        <td><a href="{% url 'home:bucket_delete' object.Key %}">Delete</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

home/templates/home/category_detail.html
{% extends 'base.html' %}

{% block content %}
    {% for category in categories %}
    <div class="btn-group">
      <a href="{{ category.get_absolute_url }}" class="btn btn-info">{{ category.name }}</a>
      <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
              aria-expanded="false">
        <span class="visually-hidden">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu">
          {% for sub in category.scategory.all %}
            <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
          {% endfor %}
      </ul>
    </div>
    {% endfor %}
    <br><br><br>
    {% for product in products %}
        <div class="card" style="width: 18rem; display: inline-block;">
    <img src="{{ product.image.url }}" class="card-img-top" alt="..." style="height: 300px;">
    <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">{{ product.description|safe }}</p>
        <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Details</a>
    </div>
    </div>
    {% endfor %}
{% endblock %}

home/templates/home/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    {% for category in categories %}
    <div class="btn-group">
      <a href="{{ category.get_absolute_url }}" class="btn btn-info">{{ category.name }}</a>
      <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
              aria-expanded="false">
        <span class="visually-hidden">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu">
          {% for sub in category.scategory.all %}
            <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
          {% endfor %}
      </ul>
    </div>
    {% endfor %}
    <br><br><br>
    {% for product in products %}
        <div class="card" style="width: 18rem; display: inline-block;">
    <img src="{{ product.image.url }}" class="card-img-top" alt="..." style="height: 300px;">
    <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">{{ product.description|safe }}</p>
        <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Details</a>
    </div>
    </div>
    {% endfor %}
{% endblock %}

home/templates/home/product.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ product.name }}</h2>
    <small>{{ product.created }}</small><br>
    <p>{{ product.price }} $</p>
    <img src="{{ product.image.url }}" style="width: 300px; height: 300px">
    <p>{{ product.description|safe}}</p><br/><br>
    <form action="{% url 'orders:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add to cart">
    </form>
{% endblock %}