accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('register/',views.UserRegsiterView.as_view(),name='user_register'),
    path('verify/',views.UserVerifyCodeView.as_view(),name='user_verify_code'),
    path('login/',views.UserLoginView.as_view(),name='user_login'),
    path('logout/',views.UserLogoutView.as_view(),name='user_logout'),
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('',views.HomeView.as_view(),name='homepage'),
    path('bucket/', views.BucketView.as_view(),name='bucket'),
    path('bucket/delete/<key>/',views.BucketObjectDeleteView.as_view(), name='bucket_delete'),
    path('bucket/dowmload/<key>/', views.BucketObjectDownloadView.as_view(), name='bucket_download'),
    path('category/<slug:category_slug>/',views.CategoryView.as_view(), name='category_detail'),
    path('products/<slug:product_slug>/', views.ProductView.as_view(), name='product_detail')

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('create/', views.CreateOrderView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='coupon_apply'),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if request.user.is_admin %}
          <a class="nav-link active"  href="/admin">Admin Panel</a>
            <a class="nav-link active"  href="{% url 'home:bucket' %}">Bucket</a>
        {% endif %}
          <a class="nav-link active"  href="{% url 'home:homepage' %}">Home</a>
          {% if request.user.is_authenticated %}
              <a class="nav-link active"  href="{% url 'orders:cart' %}">Cart {{ cart|length }}</a>
              <a class="nav-link active"  href="{% url 'accounts:user_logout' %}">Logout</a>
          {% else %}
              <a class="nav-link active"  href="{% url 'accounts:user_login' %}">Login</a>
              <a class="nav-link active"  href="{% url 'accounts:user_register' %}">Register</a>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>